# Generated by Django 5.2.5 on 2025-08-08 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Part',
        ),
    ]
