# Generated by Django 5.2.5 on 2025-08-10 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cpus', '0001_initial'),
        ('gpus', '0001_initial'),
        ('rams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpus.cpu')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpus.gpu')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rams.ram')),
            ],
        ),
    ]
