# Generated by Django 5.2.5 on 2025-08-10 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('speed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(100)])),
                ('gigabytes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
