# Generated by Django 5.2.5 on 2025-08-10 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('computer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('pc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='computer.computer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_confirm_orders', 'Can confirm orders'), ('can_mark_delivered', 'Can mark orders as delivered')],
            },
        ),
    ]
